version: "3"
services: 
  neo4j:
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=none
    ports:
      - "7474:7474"
      - "1337:1337"
      - "7687:7687"
    volumes:
      - ./data/import:/var/lib/neo4j/import
      - $HOME/neo4j/data/kegg:/data

  notebook:
    image: cbleker/jupyter-graph-notebook:latest
    ports:
      - "8888:8888"
    links:
      - neo4j:neo4j
    volumes:
      - ./work:/home/jovyan/work
      - ./data:/home/jovyan/data

